// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['base/RoomrSection', 'widgets/PhotoUploadWidget'], function(RoomrSection, PhotoUploadWidget) {
    'use strict';

    var PhotoUploadSection;
    return PhotoUploadSection = (function(_super) {

      __extends(PhotoUploadSection, _super);

      function PhotoUploadSection() {
        var photoUploadWidget;
        PhotoUploadSection.__super__.constructor.call(this, {
          name: 'photoUpload',
          title: 'Foto Upload'
        });
        photoUploadWidget = new PhotoUploadWidget();
        this.addWidget(photoUploadWidget);
      }

      return PhotoUploadSection;

    })(RoomrSection);
  });

}).call(this);
