// Generated by CoffeeScript 1.3.3
(function() {

  require(['base/EventMediator', 'backbone', 'base/AppRouter', 'sections/PhotoUploadSection', 'sections/OfferRoomSection', 'sections/SearchSection', 'sections/MainSection', 'sections/RegisterSection', 'widgets/LoginWidget'], function(EventMediator, Backbone, AppRouter, PhotoUploadSection, OfferRoomSection, SearchSection, MainSection, RegisterSection, LoginWidget) {
    'use strict';

    var app, loginWidget, mainSection, offerRoomSection, photoUploadSection, registerSection, searchSection;
    app = new AppRouter();
    loginWidget = new LoginWidget();
    loginWidget.renderInto($('#login'));
    mainSection = new MainSection();
    app.addSection(mainSection);
    searchSection = new SearchSection();
    app.addSection(searchSection);
    offerRoomSection = new OfferRoomSection();
    app.addSection(offerRoomSection);
    registerSection = new RegisterSection();
    app.addSection(registerSection);
    photoUploadSection = new PhotoUploadSection();
    app.addSection(photoUploadSection);
    return $(document).ready(function() {
      return Backbone.history.start({
        pushState: true
      });
    });
  });

}).call(this);
